language: node_js
node_js:
- stable
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - arnold.balliu@gmail.com
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm
install:
- npm install
before_script:
- export CI=false
script:
- npm test -- --coverage
deploy:
  provider: heroku
  api_key:
    secure: CmGqewh1K3NQUOqZ5cbzOKk0knl83CTXNFaGtFjIf9xnR9LJxNIeHlzFZGDjkk/ugPN6OPqo4RIJBZdac53j0Jh2WgH3UShDPsqdWwoiFFfd0c4csT5FcN5LmH3pQoj3dG+hy9xqJx5sznThIswr4kRLDDrhyB+vAUherZcmXGDUlqbNZGe20CGWLv34lrUowHHIDgWsCMS8yB1TnlPcs/u3pQ6xsFeSRyHrq+tQaPxCEZclBrS1FyhMfD+G6YC465dD1SRYYqrcRUAuEsHYxr+pxKumllm5s7BM0wI5vJ7b4XnZSsIAy0+l4eH2vwBJqc2dX44cngYnry6bNd+QkoxaB1vBzvKcTa/L5ZKUIt0CqS0MHNcVbUtwQSGKwNGIOTqbIk9myjpC5XdXMkQgDKlFm/4wpkZf9wQnjvYwW+/Claf3E9rhl46u0kPYOVRSd/dVXdlsYH8cF0rBN8HDqIUG9n8ashoPYAbd55FCyqYFzWnCCDIxEYylXV34dVldbj0/s7T0u9s+NsP5k72yaApSxUGVkE4qXNHRxTG54AVGHmkDsk6EyncORKWrwt85OfIei/qw1aXgCNv/EJYUzerOG4Qi9cFe/hCIUQvfXNI0iW7Y74r1zRG/P5I+C3arUHhNMlXDdI3Ej8RyeJWkzfSdwXNwTdrfv6S6tfhlG28=
  app: bmore911
  on:
    repo: arn95/Bmore911
